### ISSUE TITLE
/api/attack-objects throws exception when data is loaded 

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-rest-api#87]
This error prevents collections from being exported (and possibly impacts other front-end features).

```
2021-07-07T11:50:54.333Z [ERROR] Failed with error: MongoError: BSONObj size: 17419722 (0x109CDCA) is invalid. Size must be between 0 and 16793600(16MB) First element: totalCount: [ { totalCount: 10365 } ]
2021-07-07T11:50:54.341Z [HTTP] GET /api/attack-objects 200 482.602 ms - 43
(node:1021) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/Users/jtrahan/working/workspaces/ctid/federated-attack/app/attack-workbench-rest-api/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/Users/jtrahan/working/workspaces/ctid/federated-attack/app/attack-workbench-rest-api/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/Users/jtrahan/working/workspaces/ctid/federated-attack/app/attack-workbench-rest-api/node_modules/express/lib/response.js:158:21)
    at exports.retrieveAll (/Users/jtrahan/working/workspaces/ctid/federated-attack/app/attack-workbench-rest-api/app/controllers/attack-objects-controller.js:31:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Steps to reproduce:
1. [Import Enterprise ATT&CK v8.0](http://127.0.0.1:4200/collection/import-collection?url=https%253A%252F%252Fraw.githubusercontent.com%252Fmitre-attack%252Fattack-stix-data%252Fmaster%252Fenterprise-attack%252Fenterprise-attack-8.0.json)
2. GET `localhost:3000/api/attack-objects`, with or without query parameters.
3. Error will result

Note: doesn't appear to happen when no data is loaded in database. Doesn't seem to matter much which version of ATT&CK is imported (seems to occur with both 8.0 and 9.0 at least).

**Comment by ElJocko** [comment]
It looks like the problem occurs when the total size of the returned objects exceeds the MongoDB 16MB threshold. If the query returned the ATT&CK objects in an array, this wouldn't created an error, since no individual document exceeds the threshold. But the aggregation query currently returns an object that looks like this:
```
{
  totalCount: 10365,
  documents: [ ... ]
}
```
where the `totalCount` property holds the number of documents after applying the search parameters but before applying the pagination and `documents` holds the actual ATT&CK objects (after pagination). MongoDB considers this object to be the returned document, and since it contains a large set of ATT&CK objects, it exceeds the threshold.

One possible solution would be to modify the query to return an array of ATT&CK objects that fit the search parameters, and then implement the pagination in the code (rather than the way it is now, where the pagination is performed inside the aggregation query). This would look exactly the same to clients of the API, but would avoid the document size problem.
